### ISSUE TITLE
LEDs don't turn off when recorder is stopped

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/thermal-recorder#45]
The defer used to turn off the LEDs doesn't fire if thermal-recorder is killed by a signal (which is the usual way). Need to introduce some signal handlers.

**Comment by rpoletaev** [comment]
could you show me where this defer func is?

**Comment by mjs** [comment]
Argh! You have a knack for finding out of date issues :)

thermal-recorder no longer turns LEDs on and off so this is no longer an issue.
