### ISSUE TITLE
Add rate limiting to TakeSnapshot d-bus call

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/thermal-recorder#58]
If TakeSnapshot was already called recently then it should return (without error) to prevent unnecessary system load.

**Comment by rpoletaev** [comment]
I can make it with hardcoded interval (like a loglimiter) but i should to know limit value or create configurable manager for snapshots with CREATE\DELETE methods. what is best approach?

**Comment by mjs** [comment]
A hardcoded limit of 2Hz should be ok for now. Thanks!
