### ISSUE TITLE
Gracefully handle /etc/thermal-uploader.yaml not being there

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/thermal-recorder#86]
It shouldn't matter if thermal-uploader.yaml isn't there. Just don't set the device name in CPTV files if it's not.

**Comment by rpoletaev** [comment]
It is about this [code](https://github.com/TheCacophonyProject/thermal-recorder/blob/d2aff0290c7f51d37699f9f095c48aedbbb86697/cmd/thermal-recorder/cptvfilerecorder.go#L34)?

**Comment by mjs** [comment]
This issue is actually no longer relevant since #95 landed. Sorry for the confusion.
